/*!
A library for building and managing rust workspaces with batteries included.
Preamble is used by [amble](https://crates.io/crates/amble) for its core
functionality.

# Overview

Contains a number of modules for building rust workspaces with batteries included.

# Usage

```ignore,rust
use preamble::telemetry;

fn main() {
    // Initialize the tracing subscriber with 0 verbosity (only errors)
    telemetry::init_tracing_subscriber(0).unwrap();
}
```
*/

#![doc(
    html_logo_url = "https://raw.githubusercontent.com/refcell/amble/main/etc/logo.png",
    html_favicon_url = "https://raw.githubusercontent.com/refcell/amble/main/etc/favicon.ico",
    issue_tracker_base_url = "https://github.com/refcell/amble/issues/"
)]
#![warn(missing_debug_implementations, missing_docs, unreachable_pub, rustdoc::all)]
#![deny(unused_must_use, rust_2018_idioms)]
#![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]

/// Workspace Binary Crate Builders
pub mod bins;

/// Cargo Manifest Module
pub mod cargo;

/// Github Actions Workflow Module
pub mod ci;

/// Et Cetera Directory Handlers
pub mod etc;

/// Gitignore File Handler
pub mod gitignore;

/// Workspace Library Crate Builders
pub mod libs;

/// License File Helpers
pub mod license;

/// Root-level Crate Helpers
pub mod root;

/// Telemetry
///
/// The telemetry module is used by workspace projects generated by amble to
/// automatically set up tracing without needing to duplicate tracing subscriber
/// setup code in every project.
pub mod telemetry;

/// Utility Functions
pub mod utils;
